#-*- perl -*-

=encoding utf8

This file is automatically generated.  DON'T EDIT THIS FILE MANUALLY.

=cut

package Unicode::LineBreak;

# Note: Rules for H2, H3, JL, JV, JT aren't used by break() method.
our $RULES_MAP = [
    #OpClQuGlNsExSyIsPrPoNuAlIdInHyBaBbB2CbZwWjH2H3JlJvJt
    [P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,P,], # OP
    [D,P,I,P,P,P,P,P,I,I,D,D,D,D,I,I,D,D,D,P,P,D,D,D,D,D,], # CL
    [P,P,I,P,I,P,P,P,I,I,I,I,I,I,I,I,I,I,I,P,P,I,I,I,I,I,], # QU
    [I,P,I,P,I,P,P,P,I,I,I,I,I,I,I,I,I,I,I,P,P,I,I,I,I,I,], # GL
    [D,P,I,P,I,P,P,P,D,D,D,D,D,D,I,I,D,D,D,P,P,D,D,D,D,D,], # NS
    [D,P,I,P,I,P,P,P,D,D,D,D,D,D,I,I,D,D,D,P,P,D,D,D,D,D,], # EX
    [D,P,I,P,I,P,P,P,D,D,I,D,D,D,I,I,D,D,D,P,P,D,D,D,D,D,], # SY
    [D,P,I,P,I,P,P,P,D,D,I,I,D,D,I,I,D,D,D,P,P,D,D,D,D,D,], # IS
    [I,P,I,P,I,P,P,P,D,D,I,I,I,D,I,I,D,D,D,P,P,I,I,I,I,I,], # PR
    [I,P,I,P,I,P,P,P,D,D,I,I,D,D,I,I,D,D,D,P,P,D,D,D,D,D,], # PO
    [D,P,I,P,I,P,P,P,I,I,I,I,D,I,I,I,D,D,D,P,P,D,D,D,D,D,], # NU
    [D,P,I,P,I,P,P,P,D,D,I,I,D,I,I,I,D,D,D,P,P,D,D,D,D,D,], # AL
    [D,P,I,P,I,P,P,P,D,I,D,D,D,I,I,I,D,D,D,P,P,D,D,D,D,D,], # ID
    [D,P,I,P,I,P,P,P,D,D,D,D,D,I,I,I,D,D,D,P,P,D,D,D,D,D,], # IN
    [D,P,I,P,I,P,P,P,D,D,I,D,D,D,I,I,D,D,D,P,P,D,D,D,D,D,], # HY
    [D,P,I,P,I,P,P,P,D,D,D,D,D,D,I,I,D,D,D,P,P,D,D,D,D,D,], # BA
    [I,P,I,P,I,P,P,P,I,I,I,I,I,I,I,I,I,I,D,P,P,I,I,I,I,I,], # BB
    [D,P,I,P,I,P,P,P,D,D,D,D,D,D,I,I,D,P,D,P,P,D,D,D,D,D,], # B2
    [D,P,I,P,D,P,P,P,D,D,D,D,D,D,D,D,D,D,D,P,P,D,D,D,D,D,], # CB
    [D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,P,D,D,D,D,D,D,], # ZW
    [I,P,I,P,I,P,P,P,I,I,I,I,I,I,I,I,I,I,I,P,P,I,I,I,I,I,], # WJ
    [D,P,I,P,I,P,P,P,D,I,D,D,D,I,I,I,D,D,D,P,P,D,D,D,I,I,], # H2
    [D,P,I,P,I,P,P,P,D,I,D,D,D,I,I,I,D,D,D,P,P,D,D,D,D,I,], # H3
    [D,P,I,P,I,P,P,P,D,I,D,D,D,I,I,I,D,D,D,P,P,I,I,I,I,D,], # JL
    [D,P,I,P,I,P,P,P,D,I,D,D,D,I,I,I,D,D,D,P,P,D,D,D,I,I,], # JV
    [D,P,I,P,I,P,P,P,D,I,D,D,D,I,I,I,D,D,D,P,P,D,D,D,D,I,], # JT
];

1;
