/*
 * This file is automatically generated.  DON'T EDIT THIS FILE MANUALLY.
 */
#include <stddef.h>
#ifdef USE_LIBTHAI
#    include "thai/thwchar.h"
#    include "thai/thwbrk.h"
#endif /* USE_LIBTHAI */

/* Primitive types */
typedef unsigned int unichar_t;
typedef size_t propval_t;

/* Unicode string */
typedef struct {
    unichar_t *str;
    size_t len;
} unistr_t;

/* Grapheme cluster */
typedef struct {
    size_t idx; size_t len;
    size_t col;
    propval_t lbc;
    unsigned char flag;
} gcchar_t;
#define LINEBREAK_BREAK_BEFORE (2)
#define LINEBREAK_PROHIBIT_BEFORE (1)
#define LINEBREAK_FLAGS (2 | 1)

/* Property map entry */
typedef struct {
    unichar_t beg;
    unichar_t end;
    propval_t lbc;
    propval_t eaw;
    propval_t gbc;
    propval_t scr;
} mapent_t;

/* LineBreak object */
typedef struct {
    mapent_t *map;
    size_t mapsiz;
    unsigned int options;
} linebreak_t;

/* GCString object */
typedef struct {
    unichar_t *str;
    size_t len;
    gcchar_t *gcstr;
    size_t gclen;
    linebreak_t *lbobj;
} gcstring_t;


#define LINEBREAK_OPTION_EASTASIAN_CONTEXT (1)
#define PROP_UNKNOWN ((propval_t)~0)

#define M (4)
#define D (3)
#define I (2)
#define P (1)

#define MANDATORY (M)
#define DIRECT (D)
#define INDIRECT (I)
#define PROHIBITED (P)
#define URGENT (200)

/* <<< */
#define LB_BK ((propval_t)0)
#define LB_CR ((propval_t)1)
#define LB_LF ((propval_t)2)
#define LB_NL ((propval_t)3)
#define LB_SP ((propval_t)4)
#define LB_OP ((propval_t)5)
#define LB_CL ((propval_t)6)
#define LB_QU ((propval_t)7)
#define LB_GL ((propval_t)8)
#define LB_NS ((propval_t)9)
#define LB_EX ((propval_t)10)
#define LB_SY ((propval_t)11)
#define LB_IS ((propval_t)12)
#define LB_PR ((propval_t)13)
#define LB_PO ((propval_t)14)
#define LB_NU ((propval_t)15)
#define LB_AL ((propval_t)16)
#define LB_ID ((propval_t)17)
#define LB_IN ((propval_t)18)
#define LB_HY ((propval_t)19)
#define LB_BA ((propval_t)20)
#define LB_BB ((propval_t)21)
#define LB_B2 ((propval_t)22)
#define LB_CB ((propval_t)23)
#define LB_ZW ((propval_t)24)
#define LB_CM ((propval_t)25)
#define LB_WJ ((propval_t)26)
#define LB_H2 ((propval_t)27)
#define LB_H3 ((propval_t)28)
#define LB_JL ((propval_t)29)
#define LB_JV ((propval_t)30)
#define LB_JT ((propval_t)31)
#define LB_CP ((propval_t)32)
#define LB_SG ((propval_t)33)
#define LB_AI ((propval_t)34)
#define LB_SA ((propval_t)35)
#define LB_XX ((propval_t)36)

#define EA_Z ((propval_t)0)
#define EA_Na ((propval_t)1)
#define EA_N ((propval_t)2)
#define EA_A ((propval_t)3)
#define EA_W ((propval_t)4)
#define EA_H ((propval_t)5)
#define EA_F ((propval_t)6)

#define GB_CR ((propval_t)0)
#define GB_LF ((propval_t)1)
#define GB_Control ((propval_t)2)
#define GB_Extend ((propval_t)3)
#define GB_Prepend ((propval_t)4)
#define GB_SpacingMark ((propval_t)5)
#define GB_L ((propval_t)6)
#define GB_V ((propval_t)7)
#define GB_T ((propval_t)8)
#define GB_LV ((propval_t)9)
#define GB_LVT ((propval_t)10)
#define GB_Other ((propval_t)11)

#define SC_Common ((propval_t)0)
#define SC_Inherited ((propval_t)1)
#define SC_Unknown ((propval_t)2)
#define SC_Han ((propval_t)3)
#define SC_Hangul ((propval_t)4)
#define SC_Thai ((propval_t)5)
#define SC_Lao ((propval_t)6)
#define SC_Myanmar ((propval_t)7)
#define SC_Khmer ((propval_t)8)
#define SC_Tai_Le ((propval_t)9)
#define SC_New_Tai_Lue ((propval_t)10)
#define SC_Tai_Tham ((propval_t)11)
#define SC_Tai_Viet ((propval_t)12)


/* >>> */
